// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzmnbjyobcnvqcyyncvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6bW5ianlvYmNudnFjeXluY3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjA0OTAsImV4cCI6MjA2MDAzNjQ5MH0.P6yk3NR5QdCqlzREXENsaPJ2i-2c3Nw2UgBcMM_xypY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});